name: cuda_env
channels:
  - nvidia
  - rapidsai
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=4.4.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=24.2.0
  - aws-c-auth=0.7.3
  - aws-c-cal=0.6.1
  - aws-c-common=0.9.0
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.1
  - aws-c-http=0.7.11
  - aws-c-io=0.13.32
  - aws-c-mqtt=0.9.3
  - aws-c-s3=0.3.14
  - aws-c-sdkutils=0.1.12
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.21.0
  - aws-sdk-cpp=1.10.57
  - babel=2.14.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.3
  - bleach=6.1.0
  - bokeh=2.4.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.33.1
  - ca-certificates=2024.8.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.0
  - certifi=2024.8.30
  - cffi=1.17.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - comm=0.2.2
  - contourpy=1.1.1
  - cubinlinker=0.3.0
  - cuda-cudart=12.4.127
  - cuda-nvrtc=12.4.127
  - cuda-profiler-api=11.8.86
  - cuda-python=11.8.2
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudf=23.04.01
  - cuml=23.04.01
  - cupy=11.2.0
  - cycler=0.12.1
  - cytoolz=0.12.3
  - dask=2023.3.2
  - dask-core=2023.3.2
  - dask-cuda=23.04.00
  - dask-cudf=23.04.01
  - debugpy=1.8.5
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2023.3.2.1
  - dlpack=0.5
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fastavro=1.9.5
  - fastrlock=0.8.2
  - fmt=9.1.0
  - fonttools=4.53.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - gflags=2.2.2
  - glog=0.6.0
  - gmock=1.10.0
  - gtest=1.10.0
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.2
  - hyperframe=6.0.1
  - idna=3.9
  - importlib-metadata=8.5.0
  - importlib-resources=6.4.5
  - importlib_metadata=8.5.0
  - importlib_resources=6.4.5
  - ipykernel=6.29.5
  - ipython=8.12.2
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.2
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.38
  - lerc=4.0.0
  - libabseil=20230125.3
  - libarrow=10.0.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcudf=23.04.01
  - libcufft=10.9.0.58
  - libcuml=23.04.01
  - libcumlprims=23.04.00
  - libcurand=10.3.0.86
  - libcurand-dev=10.3.0.86
  - libcurl=8.8.0
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgfortran=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libgomp=14.1.0
  - libgoogle-cloud=2.12.0
  - libgrpc=1.54.3
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libnghttp2=1.58.0
  - libnuma=2.0.18
  - libopenblas=0.3.25
  - libpng=1.6.43
  - libprotobuf=3.21.12
  - libraft=23.04.01
  - libraft-headers=23.04.01
  - librmm=23.04.01
  - libsodium=1.0.18
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libthrift=0.18.1
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libzlib=1.2.13
  - llvmlite=0.39.1
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - markupsafe=2.1.5
  - matplotlib-base=3.7.3
  - matplotlib-inline=0.1.7
  - mistune=3.0.2
  - msgpack-python=1.0.8
  - munkres=1.1.4
  - nbclient=0.10.0
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - nccl=2.22.3.1
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook=7.2.2
  - notebook-shim=0.2.4
  - numba=0.56.4
  - numpy=1.23.5
  - nvtx=0.2.10
  - openjpeg=2.5.2
  - openssl=3.3.2
  - orc=1.9.0
  - overrides=7.7.0
  - packaging=24.1
  - pandas=1.5.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - partd=1.4.1
  - patsy=0.5.6
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.3
  - pooch=1.8.2
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.47
  - prompt_toolkit=3.0.47
  - protobuf=4.21.12
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptxcompiler=0.8.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=10.0.1
  - pycparser=2.22
  - pygments=2.18.0
  - pylibraft=23.04.01
  - pynvml=11.4.1
  - pyparsing=3.1.4
  - pysocks=1.7.1
  - python=3.8.19
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python_abi=3.8
  - pytz=2024.2
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - raft-dask=23.04.01
  - rdma-core=28.9
  - re2=2023.03.02
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rmm=23.04.01
  - rpds-py=0.20.0
  - s2n=1.3.49
  - scipy=1.10.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=72.1.0
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - spdlog=1.11.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - statsmodels=0.14.1
  - tblib=3.0.0
  - terminado=0.18.1
  - tinycss2=1.3.0
  - tk=8.6.14
  - tomli=2.0.1
  - toolz=0.12.1
  - tornado=6.4.1
  - traitlets=5.14.3
  - treelite=3.2.0
  - types-python-dateutil=2.9.0.20240906
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - ucx=1.14.1
  - ucx-proc=1.0.0
  - ucx-py=0.31.01
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.2.2
  - wcwidth=0.2.13
  - webcolors=24.8.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - widgetsnbextension=4.0.13
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.20.2
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - adjusttext==1.2.0
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - async-timeout==4.0.3
      - bertopic==0.16.3
      - blis==0.7.11
      - catalogue==2.0.10
      - click-plugins==1.1.1
      - cligj==0.7.2
      - cloudpathlib==0.19.0
      - colorcet==3.1.0
      - confection==0.1.5
      - cymem==2.0.8
      - cython==3.0.11
      - datasets==3.0.0
      - datashader==0.15.2
      - datashape==0.5.2
      - dill==0.3.8
      - en-core-web-sm==3.7.1
      - fiona==1.10.0
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gensim==4.3.3
      - geopandas==0.13.2
      - hdbscan==0.8.38.post1
      - huggingface-hub==0.25.0
      - kaleido==0.2.1
      - langcodes==3.4.0
      - language-data==1.2.0
      - marisa-trie==1.2.0
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - multipledispatch==1.0.0
      - multiprocess==0.70.16
      - murmurhash==1.0.10
      - networkx==3.1
      - nltk==3.9.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.68
      - nvidia-nvtx-cu12==12.1.105
      - param==2.1.1
      - pipdeptree==2.23.4
      - plotly==5.24.1
      - preshed==3.0.9
      - pyct==0.5.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pynndescent==0.5.13
      - pyproj==3.5.0
      - regex==2024.9.11
      - rich==13.8.1
      - river==0.19.0
      - safetensors==0.4.5
      - scikit-learn==1.3.2
      - sentence-transformers==2.2.2
      - sentencepiece==0.2.0
      - shapely==2.0.6
      - shellingham==1.5.4
      - smart-open==7.0.4
      - spacy==3.7.6
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - sympy==1.13.2
      - tenacity==9.0.0
      - thinc==8.2.5
      - threadpoolctl==3.5.0
      - tokenizers==0.19.1
      - torch==2.4.1
      - torchvision==0.19.1
      - tqdm==4.66.5
      - transformers==4.44.2
      - treelite-runtime==3.2.0
      - triton==3.0.0
      - typer==0.12.5
      - umap-learn==0.5.6
      - wasabi==1.1.3
      - weasel==0.4.1
      - wrapt==1.16.0
      - xarray==2023.1.0
      - xxhash==3.5.0
      - yarl==1.11.1
prefix: /home/zc_research/miniconda3/envs/cuda_env
